"use strict";

const d = document,
  root = d.getElementById("root"),
  titleBtn = d.getElementById("title"),
  banner = d.querySelector(".banner-container"),
  btnShowMain = d.getElementById("start-btn"),
  aplicationMain = d.querySelector(".aplication-main"),
  itemsToDisplay = d.querySelectorAll("[data-show]"),
  acordeonElements = d.querySelectorAll("[data-acordeon] .acordeon"),
  projectCardTemplate = d.getElementById("project-card"),
  btnMenu = d.querySelector(".menu-btn"),
  btnCloseMenu = d.querySelector(".menu-btn .close-menu"),
  btnOpenMenu = d.querySelector(".menu-btn .open-menu"),
  sidebar = d.getElementById("sidebar"),
  copyMailElements = d.querySelectorAll(".copy-mail"),
  openMailElements = d.querySelectorAll(".open-gmail"),
  messageTemplate = d.getElementById("message-template"),
  messagesContainer = d.getElementById("messages-container"),
  projectsContainer = d.querySelector(".projects-container");

export const $elements = {
  root,
  banner,
  copyMailElements,
  openMailElements,
  btnShowMain,
  titleBtn,
  btnMenu,
  btnCloseMenu,
  btnOpenMenu,
  sidebar,
  aplicationMain,
  itemsToDisplay,
  acordeonElements,
  projectsContainer,
  projectCardTemplate,
  messageTemplate,
  messagesContainer,
};
